import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        height:"100%",
        backgroundColor:"#ebebeb"
    },
    name:{
        fontSize:25,
        fontWeight:"500",
        textAlign:"center",
    },
    div:{
        padding:5,
        margin:8,
        backgroundColor:"white",
        marginTop:-28,
    },
    email:{
        textAlign:"center",
        margin:2,
        fontSize:15
    },
    scroll:{
       height:"100%"
    },
    search:{
        borderColor:"#ccc",
        borderWidth:1,
        padding:5,
        margin:8,
        borderRadius:3,
        fontSize:18,
        backgroundColor:"#fff",
        width:"60%"
    },
    card:{
        borderColor:"#ebebeb",
        borderWidth:1,
        margin:8,
        marginTop:-1,
        padding:15,
        borderRadius:3,
        backgroundColor:"white",
        flexDirection:"row",
        flexWrap:"wrap",
        alignItems:"center",
        justifyContent:"space-between"
    },
    caption:{
        fontWeight:"bold"
    },
    btn:{
        backgroundColor:"#0275d8",
        margin:8,
        marginTop:5,
        padding:5,
        borderRadius:3,
        flexDirection:"row",
        flexWrap:"wrap",
        alignItems:"center",
        justifyContent:"center"
    },
    more:{
        color:"white",
        textAlign:"center",
        fontSize:17,
        fontWeight:"bold",
        padding:2
    },
    divInner:{
        borderColor:"#ebebebeb",
        borderBottomWidth:1,
        paddingBottom:5
    },

    divInner2:{
        justifyContent:"space-around",
        flexDirection:"row",
        padding:5,
        width:"100%",
    },
    btnAssinar:{
        padding:8,
        backgroundColor:"#0275d8",
        width:150,
        borderRadius:5
    },
    btnSair:{
        padding:8,
        backgroundColor:"#ebebeb",
        width:150,
        borderRadius:5
    },
    btnText:{
        textAlign:"center",
        fontSize:16,
        fontWeight:"500"
    },
    btnText1:{
        textAlign:"center",
        color:"white",
        fontSize:16,
        fontWeight:"500"
    },
    btns:{
        flexDirection:"row",
        justifyContent:"space-around"
    },
    searchView:{
        flexDirection:"row",
        justifyContent:"space-around",
        alignItems:"center"
    },
    btnSearch:{
        padding:8,
        backgroundColor:"#0275d8",
        width:120,
        borderRadius:2,
        margin:10
    },
});